#!/bin/bash 

# Name: 			 build
# By:					 julianorchard
# Tag Added:	 09/02/2022
# Desciption:  Builds images of Kanji in the file using 4 fonts...

# Character To Render
  char=$1
  numb=$2
  file="$numb-$char"

# Output Location
  folder=$3

# File and Folder
  out="${folder}${file}.jpg"

# Colours
  fg_colour='#222222'
  bg_colour='#efdfc1'

# Specify Fonts 
  font_one='Meiryo-&-Meiryo-Italic-&-Meiryo-UI-&-Meiryo-UI-Italic'
  font_two='Noto-Serif-JP'
  font_thr='Yuji-Mai-Regular'
  font_fou='BIZ-UDGothic-&-BIZ-UDPGothic'
  
  echo "Creating ${char}."

# On Windows, Needs Magick
  magick convert -size 400x400 -pointsize 150 xc:${bg_colour} -stroke ${fg_colour} \
					-gravity NorthWest -font ${font_one} -annotate +40+5  ${char} \
					-gravity NorthEast -font ${font_two} -annotate +40-5  ${char} \
					-gravity SouthWest -font ${font_thr} -annotate +40+15 ${char} \
					-gravity SouthEast -font ${font_fou} -annotate +40+40 ${char} \
          ${out}

